appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.4.2
appReplicas: 2
containerPort: 8080
containerEnvVar:
- name: PORT
  value: "8080"
- name: AD_SERVICE_ADDR
  value: "adservice:9555"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: RECOMMENDATION_SERVICE_ADDR
  value: "recommendationservice:8080"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: CHECK_SERVICE_ADDR
  value: "checkoutservice:5050"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
servicePort: 80

